import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.aurawin.core.lang.Table;

import org.json.JSONObject;
import org.pushingpixels.substance.api.skin.SubstanceBusinessLookAndFeel;


public class formMain {


    protected JSONObject jsonEdit;
    private static boolean Loading;
    private static formMain mainForm;

    private JPanel frmMain;
    private JPanel pnlMain;
    private JPanel pnlToolbarButtons;
    private JPanel sbStatus;
    private JPanel pnlToolbar;
    private JToolBar tbCollection;

    JLabel lblStatus;
    JButton btnCollectionNew;
    JTree tvCollection;
    JTabbedPane tpPages;
    JPanel sbPosition;
    JPanel sbCaption;
    JLabel lblCollectionTitle;
    JLabel lblCollectionName;
    JButton btnOpen;
    JButton btnValidate;
    JLabel lblCollectionIndex;
    JLabel lblCollectionTotal;

    public formMain() {
        $$$setupUI$$$();
        btnCollectionNew.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                collectionTab tab = new collectionTab(mainForm.tpPages);
            }
        });

        tpPages.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                collectionTab tab = (collectionTab) tpPages.getSelectedComponent();
                setCollectionPositionStatus(tab.itemIndex, tab.itemTotal);
                setStatusMessage(tab.Filename);
                lblCollectionName.setText(tab.Name);
            }
        });
    }

    public static void setLanguage() {
        mainForm.btnCollectionNew.setToolTipText(Table.Hint.Format(Table.Hint.Add, Table.Action.a, Table.Item.JSONObject));
    }

    public static void setCollectionPositionStatus(int current, int total) {
        mainForm.lblCollectionIndex.setText(Table.Print(current));
        mainForm.lblCollectionTotal.setText(Table.Print(total));
    }

    public static void setStatusMessage(String Status) {
        mainForm.lblStatus.setText(Status);
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new SubstanceBusinessLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        Loading = true;
        JFrame frame = new JFrame("formMain");
        mainForm = new formMain();
        frame.setContentPane(mainForm.frmMain);
        frame.setPreferredSize(new Dimension(640, 480));

        setLanguage();

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        Loading = false;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        frmMain = new JPanel();
        frmMain.setLayout(new CardLayout(0, 0));
        frmMain.setMinimumSize(new Dimension(640, 480));
        frmMain.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        pnlMain = new JPanel();
        pnlMain.setLayout(new BorderLayout(0, 0));
        frmMain.add(pnlMain, "Collection");
        pnlToolbar = new JPanel();
        pnlToolbar.setLayout(new BorderLayout(0, 0));
        pnlMain.add(pnlToolbar, BorderLayout.NORTH);
        tbCollection = new JToolBar();
        tbCollection.setFloatable(false);
        pnlToolbar.add(tbCollection, BorderLayout.CENTER);
        pnlToolbarButtons = new JPanel();
        pnlToolbarButtons.setLayout(new FlowLayout(FlowLayout.LEFT, 2, 1));
        tbCollection.add(pnlToolbarButtons);
        pnlToolbarButtons.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        btnCollectionNew = new JButton();
        btnCollectionNew.setIcon(new ImageIcon(getClass().getResource("/icons/default/new_16.png")));
        btnCollectionNew.setIconTextGap(4);
        btnCollectionNew.setPressedIcon(new ImageIcon(getClass().getResource("/icons/pressed/new_16.png")));
        btnCollectionNew.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/rollover/new_16.png")));
        btnCollectionNew.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/icons/rollover-pressed/new_16.png")));
        btnCollectionNew.setSelectedIcon(new ImageIcon(getClass().getResource("/icons/pressed/new_16.png")));
        btnCollectionNew.setText("");
        btnCollectionNew.setVerticalAlignment(0);
        btnCollectionNew.setVerticalTextPosition(0);
        pnlToolbarButtons.add(btnCollectionNew);
        btnOpen = new JButton();
        btnOpen.setText("");
        pnlToolbarButtons.add(btnOpen);
        btnValidate = new JButton();
        btnValidate.setText("Validate");
        pnlToolbarButtons.add(btnValidate);
        final Spacer spacer1 = new Spacer();
        pnlToolbarButtons.add(spacer1);
        lblCollectionTitle = new JLabel();
        lblCollectionTitle.setHorizontalAlignment(0);
        lblCollectionTitle.setHorizontalTextPosition(0);
        lblCollectionTitle.setText("Collection Editor");
        pnlToolbarButtons.add(lblCollectionTitle);
        final Spacer spacer2 = new Spacer();
        pnlToolbarButtons.add(spacer2);
        lblCollectionName = new JLabel();
        lblCollectionName.setText("");
        pnlToolbarButtons.add(lblCollectionName);
        sbStatus = new JPanel();
        sbStatus.setLayout(new BorderLayout(0, 0));
        pnlMain.add(sbStatus, BorderLayout.SOUTH);
        sbStatus.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        sbPosition = new JPanel();
        sbPosition.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, true));
        sbPosition.setMaximumSize(new Dimension(32767, 25));
        sbPosition.setPreferredSize(new Dimension(105, 24));
        sbStatus.add(sbPosition, BorderLayout.WEST);
        sbPosition.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        lblCollectionIndex = new JLabel();
        lblCollectionIndex.setText("");
        sbPosition.add(lblCollectionIndex, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCollectionTotal = new JLabel();
        lblCollectionTotal.setAlignmentX(0.0f);
        lblCollectionTotal.setText("");
        sbPosition.add(lblCollectionTotal, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sbCaption = new JPanel();
        sbCaption.setLayout(new BorderLayout(0, 0));
        sbStatus.add(sbCaption, BorderLayout.CENTER);
        sbCaption.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-4473925)));
        lblStatus = new JLabel();
        lblStatus.setPreferredSize(new Dimension(0, 24));
        lblStatus.setText("");
        sbCaption.add(lblStatus, BorderLayout.CENTER);
        tpPages = new JTabbedPane();
        tpPages.setMinimumSize(new Dimension(2, 20));
        pnlMain.add(tpPages, BorderLayout.CENTER);
        tpPages.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return frmMain;
    }
}
