import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

//import collectionTab;


/**
 * Created by Andrew on 9/2/2015.
 */
public class MachupTab {
    JTabbedPane tpPages;
    JPanel pnlCollectionModel;
    JPanel pnlCollectionClient;
    JPanel pnlCollectionTools;
    JButton btnCollectionEditorAdd;
    JButton btnCollectionEditorDelete;
    JLabel lblCollectionInputName;
    JTextField txtCollectionInputName;
    JLabel lblCollectionInputValue;
    JComboBox cbCollectionInputValue;
    JScrollPane spTreeView;
    JTree tvCollection;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tpPages = new JTabbedPane();
        panel1.add(tpPages, BorderLayout.CENTER);
        pnlCollectionModel = new JPanel();
        pnlCollectionModel.setLayout(new BorderLayout(0, 0));
        pnlCollectionModel.setEnabled(true);
        tpPages.addTab("Untitled", pnlCollectionModel);
        tpPages.setEnabledAt(0, false);
        pnlCollectionClient = new JPanel();
        pnlCollectionClient.setLayout(new BorderLayout(0, 0));
        pnlCollectionModel.add(pnlCollectionClient, BorderLayout.CENTER);
        pnlCollectionClient.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        pnlCollectionTools = new JPanel();
        pnlCollectionTools.setLayout(new GridLayoutManager(1, 6, new Insets(0, 0, 0, 0), -1, -1));
        pnlCollectionClient.add(pnlCollectionTools, BorderLayout.NORTH);
        pnlCollectionTools.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        btnCollectionEditorAdd = new JButton();
        btnCollectionEditorAdd.setIcon(new ImageIcon(getClass().getResource("/icons/default/add_16.png")));
        btnCollectionEditorAdd.setIconTextGap(4);
        btnCollectionEditorAdd.setPressedIcon(new ImageIcon(getClass().getResource("/icons/pressed/add_16.png")));
        btnCollectionEditorAdd.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/rollover/add_16.png")));
        btnCollectionEditorAdd.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/icons/rollover-pressed/add_16.png")));
        btnCollectionEditorAdd.setSelectedIcon(new ImageIcon(getClass().getResource("/icons/pressed/add_16.png")));
        btnCollectionEditorAdd.setText("");
        btnCollectionEditorAdd.setVerticalAlignment(0);
        btnCollectionEditorAdd.setVerticalTextPosition(0);
        pnlCollectionTools.add(btnCollectionEditorAdd, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCollectionEditorDelete = new JButton();
        btnCollectionEditorDelete.setIcon(new ImageIcon(getClass().getResource("/icons/default/delete_16.png")));
        btnCollectionEditorDelete.setLabel("");
        btnCollectionEditorDelete.setPressedIcon(new ImageIcon(getClass().getResource("/icons/pressed/delete_16.png")));
        btnCollectionEditorDelete.setRolloverEnabled(true);
        btnCollectionEditorDelete.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/rollover/delete_16.png")));
        btnCollectionEditorDelete.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/icons/rollover-pressed/delete_16.png")));
        btnCollectionEditorDelete.setSelectedIcon(new ImageIcon(getClass().getResource("/icons/pressed/delete_16.png")));
        btnCollectionEditorDelete.setText("");
        pnlCollectionTools.add(btnCollectionEditorDelete, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCollectionInputName = new JLabel();
        lblCollectionInputName.setText("Name");
        pnlCollectionTools.add(lblCollectionInputName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCollectionInputName = new JTextField();
        pnlCollectionTools.add(txtCollectionInputName, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 28), new Dimension(150, 28), null, 0, false));
        lblCollectionInputValue = new JLabel();
        lblCollectionInputValue.setText("Value");
        pnlCollectionTools.add(lblCollectionInputValue, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbCollectionInputValue = new JComboBox();
        cbCollectionInputValue.setEditable(true);
        pnlCollectionTools.add(cbCollectionInputValue, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spTreeView = new JScrollPane();
        pnlCollectionClient.add(spTreeView, BorderLayout.CENTER);
        spTreeView.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        tvCollection = new JTree();
        tvCollection.setDropMode(DropMode.ON_OR_INSERT);
        tvCollection.setEnabled(true);
        tvCollection.setFocusCycleRoot(true);
        tvCollection.setFocusTraversalPolicyProvider(true);
        tvCollection.setInvokesStopCellEditing(true);
        tvCollection.setLargeModel(true);
        tvCollection.setRootVisible(true);
        tvCollection.putClientProperty("JTree.lineStyle", "Angled");
        spTreeView.setViewportView(tvCollection);
    }
}
