package com.aurawin.jetac;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.pushingpixels.substance.api.skin.SubstanceBusinessLookAndFeel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

//import collectionTab;


/**
 * Created by Andrew on 9/2/2015.
 */
public class MachupTab {
    private static MachupTab machupTab;
    private static itmObject RuntimeObject;

    JTabbedPane tpPages;
    JPanel pnlSimpleClient;
    JPanel pnlSimpleTools;
    JButton btnCollectionEditorAdd;
    JButton btnCollectionEditorDelete;
    JLabel lblCollectionInputName;
    JTextField txtCollectionInputName;
    JLabel lblCollectionInputValue;
    JTextField cbCollectionInputValue;
    JPanel pnlMain;
    JButton btnState;
    JPanel pnlObject;
    JButton btnAddSimple;
    JButton btnAddObject;
    JButton btnAddArray;
    JPanel pnlArray;
    JPanel tpSimple;
    JPanel tpObject;
    JPanel tpArray;
    JPanel pnlObjectTools;
    JPanel pnlObjectView;
    JPanel tpRuntime;
    JPanel pnlItemClient;
    JPanel pnlObjectVIewClient;
    JScrollPane spRuntime;


    itmWrapper pnlWrapper;

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new SubstanceBusinessLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFrame frame = new JFrame("MachupTab");
        machupTab = new MachupTab();
        frame.setContentPane(machupTab.pnlMain);
        frame.setPreferredSize(new Dimension(640, 480));
        machupTab.tpPages.setSelectedIndex(3);

        machupTab.pnlWrapper = new itmWrapper(machupTab.spRuntime);
        RuntimeObject = new itmObject(machupTab.pnlWrapper);


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);


    }

    public MachupTab() {
        btnCollectionEditorAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new BorderLayout(0, 0));
        tpPages = new JTabbedPane();
        pnlMain.add(tpPages, BorderLayout.CENTER);
        tpSimple = new JPanel();
        tpSimple.setLayout(new BorderLayout(0, 0));
        tpSimple.setEnabled(true);
        tpPages.addTab("Simple", tpSimple);
        pnlSimpleClient = new JPanel();
        pnlSimpleClient.setLayout(new BorderLayout(0, 0));
        tpSimple.add(pnlSimpleClient, BorderLayout.CENTER);
        pnlSimpleClient.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        pnlSimpleTools = new JPanel();
        pnlSimpleTools.setLayout(new GridLayoutManager(1, 6, new Insets(0, 0, 0, 0), -1, -1));
        pnlSimpleClient.add(pnlSimpleTools, BorderLayout.NORTH);
        btnCollectionEditorAdd = new JButton();
        btnCollectionEditorAdd.setIcon(new ImageIcon(getClass().getResource("/icons/default/add_16.png")));
        btnCollectionEditorAdd.setIconTextGap(4);
        btnCollectionEditorAdd.setPressedIcon(new ImageIcon(getClass().getResource("/icons/pressed/add_16.png")));
        btnCollectionEditorAdd.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/rollover/add_16.png")));
        btnCollectionEditorAdd.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/icons/rollover-pressed/add_16.png")));
        btnCollectionEditorAdd.setSelectedIcon(new ImageIcon(getClass().getResource("/icons/pressed/add_16.png")));
        btnCollectionEditorAdd.setText("");
        btnCollectionEditorAdd.setVerticalAlignment(0);
        btnCollectionEditorAdd.setVerticalTextPosition(0);
        pnlSimpleTools.add(btnCollectionEditorAdd, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCollectionEditorDelete = new JButton();
        btnCollectionEditorDelete.setIcon(new ImageIcon(getClass().getResource("/icons/default/delete_16.png")));
        btnCollectionEditorDelete.setText("");
        btnCollectionEditorDelete.setPressedIcon(new ImageIcon(getClass().getResource("/icons/pressed/delete_16.png")));
        btnCollectionEditorDelete.setRolloverEnabled(true);
        btnCollectionEditorDelete.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/rollover/delete_16.png")));
        btnCollectionEditorDelete.setRolloverSelectedIcon(new ImageIcon(getClass().getResource("/icons/rollover-pressed/delete_16.png")));
        btnCollectionEditorDelete.setSelectedIcon(new ImageIcon(getClass().getResource("/icons/pressed/delete_16.png")));
        btnCollectionEditorDelete.setText("");
        pnlSimpleTools.add(btnCollectionEditorDelete, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCollectionInputName = new JLabel();
        lblCollectionInputName.setText("Name");
        pnlSimpleTools.add(lblCollectionInputName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCollectionInputName = new JTextField();
        pnlSimpleTools.add(txtCollectionInputName, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 28), new Dimension(100, 28), null, 0, false));
        lblCollectionInputValue = new JLabel();
        lblCollectionInputValue.setText("Value");
        pnlSimpleTools.add(lblCollectionInputValue, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbCollectionInputValue = new JTextField();
        cbCollectionInputValue.setEditable(true);
        pnlSimpleTools.add(cbCollectionInputValue, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 28), null, 0, false));
        tpObject = new JPanel();
        tpObject.setLayout(new GridBagLayout());
        tpObject.setAutoscrolls(true);
        tpPages.addTab("Object", tpObject);
        tpObject.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        pnlItemClient = new JPanel();
        pnlItemClient.setLayout(new GridBagLayout());
        pnlItemClient.setAlignmentX(0.0f);
        pnlItemClient.setAlignmentY(0.0f);
        pnlItemClient.setAutoscrolls(true);
        pnlItemClient.setMinimumSize(new Dimension(-1, 124));
        pnlItemClient.setPreferredSize(new Dimension(-1, 132));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        tpObject.add(pnlItemClient, gbc);
        pnlObject = new JPanel();
        pnlObject.setLayout(new BorderLayout(0, 0));
        pnlObject.setAlignmentX(0.0f);
        pnlObject.setPreferredSize(new Dimension(0, 132));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlItemClient.add(pnlObject, gbc);
        pnlObjectTools = new JPanel();
        pnlObjectTools.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        pnlObjectTools.setAlignmentX(0.0f);
        pnlObjectTools.setAlignmentY(0.0f);
        pnlObjectTools.setMinimumSize(new Dimension(32, 32));
        pnlObjectTools.setPreferredSize(new Dimension(32, 148));
        pnlObject.add(pnlObjectTools, BorderLayout.WEST);
        btnState = new JButton();
        btnState.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/arrowhead_down_16.png")));
        btnState.setPreferredSize(new Dimension(32, 32));
        btnState.setText("");
        pnlObjectTools.add(btnState);
        btnAddArray = new JButton();
        btnAddArray.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/attribute_16.png")));
        btnAddArray.setPreferredSize(new Dimension(32, 32));
        btnAddArray.setText("");
        pnlObjectTools.add(btnAddArray);
        btnAddObject = new JButton();
        btnAddObject.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/insert_row_16.png")));
        btnAddObject.setPreferredSize(new Dimension(32, 32));
        btnAddObject.setText("");
        pnlObjectTools.add(btnAddObject);
        btnAddSimple = new JButton();
        btnAddSimple.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/list_16.png")));
        btnAddSimple.setPreferredSize(new Dimension(32, 32));
        btnAddSimple.setText("");
        pnlObjectTools.add(btnAddSimple);
        pnlObjectView = new JPanel();
        pnlObjectView.setLayout(new BorderLayout(0, 0));
        pnlObjectView.setAlignmentX(0.0f);
        pnlObjectView.setAlignmentY(0.0f);
        pnlObject.add(pnlObjectView, BorderLayout.CENTER);
        pnlObjectVIewClient = new JPanel();
        pnlObjectVIewClient.setLayout(new GridBagLayout());
        pnlObjectView.add(pnlObjectVIewClient, BorderLayout.CENTER);
        tpArray = new JPanel();
        tpArray.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tpPages.addTab("Array", tpArray);
        pnlArray = new JPanel();
        pnlArray.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        tpArray.add(pnlArray, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        panel1.setAlignmentX(0.0f);
        panel1.setAlignmentY(0.0f);
        pnlArray.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(40, -1), new Dimension(40, 24), new Dimension(40, -1), 0, false));
        final JButton button1 = new JButton();
        button1.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/arrowhead_down_16.png")));
        button1.setPreferredSize(new Dimension(32, 32));
        button1.setText("");
        panel1.add(button1);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1);
        final JButton button2 = new JButton();
        button2.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/list_16.png")));
        button2.setPreferredSize(new Dimension(32, 32));
        button2.setText("");
        panel1.add(button2);
        final JButton button3 = new JButton();
        button3.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/insert_row_16.png")));
        button3.setPreferredSize(new Dimension(32, 32));
        button3.setText("");
        panel1.add(button3);
        final JButton button4 = new JButton();
        button4.setIcon(new ImageIcon(getClass().getResource("/theme/light/button/default/attribute_16.png")));
        button4.setPreferredSize(new Dimension(32, 32));
        button4.setText("");
        panel1.add(button4);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        pnlArray.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tpRuntime = new JPanel();
        tpRuntime.setLayout(new BorderLayout(0, 0));
        tpRuntime.setAlignmentX(0.5f);
        tpRuntime.setAlignmentY(0.5f);
        tpRuntime.setAutoscrolls(false);
        tpRuntime.setMinimumSize(new Dimension(-1, -1));
        tpRuntime.setPreferredSize(new Dimension(-1, -1));
        tpRuntime.setToolTipText("Testing 1234");
        tpPages.addTab("Runtime", tpRuntime);
        spRuntime = new JScrollPane();
        spRuntime.setHorizontalScrollBarPolicy(31);
        tpRuntime.add(spRuntime, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
